boot_command = "<esc><wait10><esc><esc><enter><wait>set gfxpayload=1024x768<enter>linux /install/vmlinuz preseed/url=http://{{.HTTPIP}}:{{.HTTPPort}}/${var.os_type}.cfg debian-installer=en_US.UTF-8 auto locale=en_US.UTF-8 kbd-chooser/method=us hostname={{.Name}} fb=false debconf/frontend=noninteractive keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA keyboard-configuration/variant=USA console-setup/ask_detect=false <enter>initrd /install/initrd.gz<enter>boot<enter>"
iso_checksum = "f11bda2f2caed8f420802b59f382c25160b114ccc665dbac9c5046e7fceaced2"
iso_url = "http://cdimage.ubuntu.com/ubuntu-legacy-server/releases/${var.os_version}/release/ubuntu-${var.os_version}-legacy-server-amd64.iso"
os_name = "focal"
os_type = "server"
os_version = "20.04.1"