Vagrant.configure('2') do |config|
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.customize ["modifyvm", :id, "--memory", 4096]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", "64"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    v.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
  end
    v.trigger.after :up, :reload do |trigger|
      trigger.info = "Setting VM display resolution"
      trigger.run = {inline: "vboxmanage controlvm \"dev_vm_full\" setvideomodehint 1600 1200 32"}
    end
end