
locals {
  adds_output_directory = "${var.export_drive}\\${var.timestamp}.${var.os_name}.adds"
  adds_vm_name          = "${var.vm_name}.adds"
}

source "hyperv-vmcx" "autogenerated_1" {
  clone_from_vmcx_path = "${var.base_output_directory}"
  communicator         = "${var.communicator}"
  cpus                 = "${var.cpus}"
  disk_block_size      = "${var.disk_block_size}"
  generation           = "${var.generation}"
  headless             = "${var.headless}"
  keep_registered      = "${var.keep_registered}"
  memory               = "${var.memory}"
  output_directory     = "${local.adds_output_directory}"
  shutdown_command     = "${var.shutdown_command}"
  skip_export          = "${var.skip_export}"
  ssh_password         = "${var.ssh_password}"
  ssh_timeout          = "${var.ssh_timeout}"
  ssh_username         = "${var.ssh_username}"
  switch_name          = "${var.switch_name}"
  vm_name              = "${var.vm_name}"
}

build {
  sources = ["source.hyperv-vmcx.autogenerated_1"]

  provisioner "file" {
    destination = "${var.home}"
    source      = "${var.files_dir}"
  }

  provisioner "shell" {
    environment_vars  = ["PASSWORD=${var.ssh_password}", "USERNAME=${var.ssh_username}"]
    expect_disconnect = true
    pause_before      = "10s"
    scripts           = ["${var.scripts_dir}/tools.sh", "${var.scripts_dir}/${var.os_type}.sh"]
  }

  post-processor "compress" {
    keep_input_artifact = false
    format              = ".zip"
    output              = "${var.zip_directory}.adds.zip"
  }
}
