source "hyperv-iso" "base" {
  boot_command     = ["${var.boot_command}"]
  boot_wait        = "${var.boot_wait}"
  communicator     = "${var.communicator}"
  cpus             = "${var.cpus}"
  disk_block_size  = "${var.disk_block_size}"
  disk_size        = "${var.disk_size}"
  generation       = "${var.generation}"
  headless         = "${var.headless}"
  http_directory   = "${var.http_directory}"
  iso_checksum     = "${var.iso_checksum}"
  iso_url          = "${var.iso_url}"
  keep_registered  = "${var.keep_registered}"
  memory           = "${var.memory}"
  output_directory = "${var.base_output_directory}"
  shutdown_command = "${var.shutdown_command}"
  ssh_password     = "${var.ssh_password}"
  ssh_timeout      = "${var.ssh_timeout}"
  ssh_username     = "${var.ssh_username}"
  switch_name      = "${var.switch_name}"
  vm_name          = "${var.base_vm_name}"
}

source "hyperv-iso" "full" {
  boot_command     = ["${var.boot_command}"]
  boot_wait        = "${var.boot_wait}"
  communicator     = "${var.communicator}"
  cpus             = "${var.cpus}"
  disk_block_size  = "${var.disk_block_size}"
  disk_size        = "${var.disk_size}"
  generation       = "${var.generation}"
  headless         = "${var.headless}"
  http_directory   = "${var.http_directory}"
  iso_checksum     = "${var.iso_checksum}"
  iso_url          = "${var.iso_url}"
  keep_registered  = "${var.keep_registered}"
  memory           = "${var.memory}"
  output_directory = "${var.full_output_directory}"
  shutdown_command = "${var.shutdown_command}"
  skip_export      = "${var.skip_export}"
  ssh_password     = "${var.ssh_password}"
  ssh_timeout      = "${var.ssh_timeout}"
  ssh_username     = "${var.ssh_username}"
  switch_name      = "${var.switch_name}"
  vm_name          = "${var.full_vm_name}"
}