# files.yml
---
- name: Clear disposable files and directories
  hosts: all
  become: true

  tasks:
    - name: Capture disk usage before performing any operations
      command: df / -hBM
      when: clear_disk_usage_pre is undefined
      register: clear_disk_usage_pre
    
    - name: Setup dpkg excludes for linux-firmware
      lineinfile:
        path: /etc/dpkg/dpkg.cfg.d/excludes
        line: "{{ item }}"
        create: yes
        mode: "644"
      loop:
        - "path-exclude=/lib/firmware/*"
        - "path-exclude=/usr/share/doc/linux-firmware/*"

    - name: Clean directories & files
      file:
        path: "{{ item }}"
        state: absent
      register: clean_complete
      changed_when: clean_complete is undefined 
      loop:
        - /lib/firmware
        - /usr/share/doc
        - /var/cache
        - /var/log
        - /var/tmp
        - /var/lib/systemd/random-seed
        - /root/.wget-hsts

    - name: Capture disk usage after performing operations
      command: df / -hBM
      when: clear_disk_usage_post is undefined
      register: clear_disk_usage_post

    - name: Print disk usage metrics
      debug:
        msg:
          - "Disk usage before:"
          - "{{ clear_disk_usage_pre.stdout_lines }}"
          - "Disk usage after:"
          - "{{ clear_disk_usage_post.stdout_lines }}"