# files.yml
---
- name: Clear disposable files and directories
  hosts: all
  become: true

  tasks:
    - name: Capture disk usage before performing any operations
      command: df / -hBM
      when: clear_disk_usage_pre is undefined
      register: clear_disk_usage_pre

    - name: Setup dpkg excludes for linux-firmware
      lineinfile:
        path: /etc/dpkg/dpkg.cfg.d/excludes
        line: "{{ item }}"
        create: yes
        mode: "644"
      loop:
        - "path-exclude=/lib/firmware/*"
        - "path-exclude=/usr/share/doc/linux-firmware/*"

    - name: Get directory stats
      stat:
        path: "{{ item }}"
      register: directory_stats
      loop:
        - /lib/firmware
        - /usr/share/doc
        - /var/cache
        - /var/log
        - /var/tmp
        - /tmp
        - /home/vagrant/.cache

    - name: Delete directories
      file:
        path: "{{ item.stat.path }}"
        state: absent
      loop: "{{ directory_stats.results }}"

    - name: Delete files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/systemd/random-seed
        - /root/.wget-hsts

    - name: Create directory
      file:
        path: "{{ item.stat.path }}"
        state: directory
        owner: "{{ item.stat.pw_name }}"
        group: "{{ item.stat.gr_name }}"
        mode: "{{ item.stat.mode }}"
      loop: "{{ directory_stats.results }}"

    - name: Autoremove packages and clean apt cache
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: no

    - name: Capture disk usage after performing operations
      command: df / -hBM
      when: clear_disk_usage_post is undefined
      register: clear_disk_usage_post

    - name: Print disk usage metrics
      debug:
        msg:
          - "Disk usage before:"
          - "{{ clear_disk_usage_pre.stdout_lines }}"
          - "Disk usage after:"
          - "{{ clear_disk_usage_post.stdout_lines }}"
