# upgrades.yml
---
- name: Install latest OS updates
  hosts: all
  become: true

  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
      notify:
      - Refresh facts
      - Check for kernel dependent packages
      - Reboot VM

    - name: Capture box creation date
      shell:
        cmd: date > /etc/vagrant_box_build_date
        creates: /etc/vagrant_box_build_date

  handlers:
    - name: Refresh facts
      setup:
    - name: Check for kernel dependent packages
      apt:
        update_cache: yes
        state: present
        pkg:
          - "linux-tools-{{ ansible_facts.kernel }}"
          - "linux-cloud-tools-{{ ansible_facts.kernel }}"      
    - name: Reboot VM
      reboot:
