# upgrades.yml
---
- name: Install latest OS updates
  hosts: all
  become: true

  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
      notify: Reboot VM

    - name: Install list of packages
      apt:
        update_cache: yes
        state: present
        pkg:
          - "linux-tools-{{ ansible_facts['ansible_kernel'] }}"
          - "linux-cloud-tools-{{ ansible_facts['ansible_kernel'] }}"

    - name: Capture box creation date
      shell:
        cmd: date > /etc/vagrant_box_build_date
        creates: /etc/vagrant_box_build_date

  handlers:
    - name: Reboot VM
      reboot:
