# user_base.yml
---
- name: Configure base user settings
  hosts: all

  tasks:
    - name: Create a working directory if it does not already exist
      file:
        path: "{{ ansible_facts['user_dir'] }}/code"
        state: directory
        mode: "755"

    - name: Suppress Ubuntu Welcome Wizard
      file:
        path: "{{ ansible_facts['user_dir'] }}/.config/gnome-initial-setup-done"
        state: touch
        mode: "664"

    - name: Set favorite apps
      dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.gedit.desktop', 'firefox.desktop', 'gnome-control-center.desktop']"
        state: present

    - name: Disable lockscreen
      dconf:
        key: "/org/gnome/desktop/session/idle-delay"
        value: "uint32 0"
        state: present

    - name: Set text scaling
      dconf:
        key: "/org/gnome/desktop/interface/text-scaling-factor"
        value: "1.25"
        state: present

    - name: Enable click to minimize
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/click-action"
        value: "'minimize'"
        state: present

    - name: Default NumLock to be enabled
      dconf:
        key: "org/gnome/desktop/peripherals/keyboard/numlock-state"
        value: "true"
        state: present

    - name: Configure NumLock state to be remembered
      dconf:
        key: "org/gnome/desktop/peripherals/keyboard/remember-numlock-state"
        value: "true"
        state: present